# Generated by Django 5.2.9 on 2025-12-03 13:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('central', 'Central Server'), ('local', 'Local Development'), ('edge', 'Edge Device'), ('desktop', 'Desktop/Laptop'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('platform', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=8000)),
                ('public_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('unreachable', 'Unreachable')], default='offline', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('registration_token', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('build', models.CharField(blank=True, max_length=50)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_nodes', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'db_table': 'nodes',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='NodeCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_gpu', models.BooleanField(default=False)),
                ('has_camera', models.BooleanField(default=False)),
                ('has_gpio', models.BooleanField(default=False)),
                ('has_lora', models.BooleanField(default=False)),
                ('can_run_django', models.BooleanField(default=True)),
                ('can_run_celery', models.BooleanField(default=True)),
                ('can_run_websocket', models.BooleanField(default=True)),
                ('storage_gb', models.PositiveIntegerField(default=0)),
                ('ram_gb', models.PositiveIntegerField(default=0)),
                ('cpu_cores', models.PositiveIntegerField(default=1)),
                ('available_modules', models.JSONField(default=list)),
                ('enabled_modules', models.JSONField(default=list)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Node Capability',
                'verbose_name_plural': 'Node Capabilities',
                'db_table': 'node_capabilities',
            },
        ),
        migrations.CreateModel(
            name='NodeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('registered', 'Node Registered'), ('online', 'Node Online'), ('offline', 'Node Offline'), ('maintenance', 'Maintenance Started'), ('updated', 'Node Updated'), ('capability_changed', 'Capability Changed'), ('module_enabled', 'Module Enabled'), ('module_disabled', 'Module Disabled'), ('error', 'Error'), ('warning', 'Warning')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Node Event',
                'verbose_name_plural': 'Node Events',
                'db_table': 'node_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('cpu_percent', models.FloatField(default=0)),
                ('memory_percent', models.FloatField(default=0)),
                ('memory_used_mb', models.PositiveIntegerField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('disk_used_gb', models.FloatField(default=0)),
                ('network_bytes_sent', models.BigIntegerField(default=0)),
                ('network_bytes_recv', models.BigIntegerField(default=0)),
                ('requests_per_minute', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Node Metric',
                'verbose_name_plural': 'Node Metrics',
                'db_table': 'node_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_type'], name='nodes_node_ty_d7cf3e_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['status'], name='nodes_status_6ffb98_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['hostname'], name='nodes_hostnam_dfa276_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['last_seen'], name='nodes_last_se_2ac632_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeevent',
            index=models.Index(fields=['node', 'event_type'], name='node_events_node_id_7bc829_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeevent',
            index=models.Index(fields=['created_at'], name='node_events_created_9941ab_idx'),
        ),
        migrations.AddIndex(
            model_name='nodemetric',
            index=models.Index(fields=['node', 'recorded_at'], name='node_metric_node_id_fd76cf_idx'),
        ),
    ]
